### ISSUE TITLE
Stop the slideshow 

### ISSUE THREAD

**Issue by gnuget** [rip747/Yahoo-style-news-slider-for-jQuery#1]
This is not a issue, is a feature request (in fact maybe is already in the code and  is only a lack of documentation)

 i want to the user  be able to "stop" the slideshow. 

I read the code and i found to there is an option for turn off and on the slideshow var but i don't found how execute that methods from out side of the library, is this possible? 

Thanks!

David.

**Comment by rip747** [comment]
are you talking about stopping the slideshow when someone hovers anywhere over the content slider? if so, that is already included in the plugin. the slideshow stops automatically when the cursor is over the content slider if the slideshow is enabled.

**Comment by gnuget** [comment]
no, i talking about  stopping the slideshow when the user do  click on another place of the page (in a button)  i want have the control of the slideshow, for stop it and start it when my app require it

I think to i need fire the  method:  slideshow.on() and slideshow.off()  but i don't know how execute that methods outside of the plugin.

$('myslideshow').accessNews('slideshow','off');  or something like that? 

Thanks.

**Comment by rip747** [comment]
thanks for clearing that up for me :) 
you're not going to be able to call the slideshow object methods directly since they aren't exposed by the plugin. personally i don't need this sort of feature (yet?) and i'm still trying to get the gist of some bugs and design stuff worked out. you are more then welcomed to fork the project and hack at it.

**Comment by gnuget** [comment]
All right.

Thank you :)
